### ISSUE TITLE
Support authentication and authorization for Pulsar Manager (MVP)

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar-manager#14]
Give priority to supporting JWT.

We will use this issue to track authentication and authorization

- [x] Support token management (https://github.com/apache/pulsar-manager/pull/205)
- [x] Support authorization at the namespace level (https://github.com/apache/pulsar-manager/pull/205)
- [x] Support authorization at the topic level (https://github.com/apache/pulsar-manager/pull/205)
- [x] Support for third-party logins such as GitHub (https://github.com/apache/pulsar-manager/pull/222)
- [x] Support management of user (https://github.com/apache/pulsar-manager/pull/226)
- [x] Support role and user binding (https://github.com/apache/pulsar-manager/pull/231)
- [x] Support management of role (https://github.com/apache/pulsar-manager/pull/231)
   - [x] Create, delete, update and list
   - [x] Support the binding of roles and resources
   - [x] Support role isolation between tenants
- [x] Supports cache tenants in the backend (https://github.com/apache/pulsar-manager/pull/231)
- [x] Supports cache namespace in the backend (https://github.com/apache/pulsar-manager/pull/231)
- [ ] Support TLS authentication
- [x] The front end shows the content according to roles (https://github.com/apache/pulsar-manager/pull/238)

**Comment by shustsud** [comment]
I would like to add authentication between BE and Brokers.
I'm planning to use Authentication class in pulsar-client-api package.
 - [Authentication.java](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Authentication.java)
 - [AuthenticationFactory.java](https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/AuthenticationFactory.java)

**Comment by tuteng** [comment]
Our design documents for authorization and authentication are almost complete. If you are interested in the authorization and authentication features of pulsar-manager, you can continue to pay attention to them. @shustsud

**Comment by shustsud** [comment]
@tuteng
thank you for your comment!


> Our design documents for authorization and authentication are almost complete.

Could you show me the design document?

**Comment by tuteng** [comment]
@shustsud We are in the process of final improvement. If there is no problem, it should be sent out in the near future.

**Comment by shustsud** [comment]
@tuteng
Thanks for your comment!

I wait for the project update.

**Comment by shustsud** [comment]
@tuteng

> We are in the process of final improvement. If there is no problem, it should be sent out in the near future.

Is there any update about Other than JWT?
 - https://github.com/apache/pulsar-manager/pull/203

I'm thinking to implement another authentication between BE and Brokers. (TLS, Athenz, etc.)
