### ISSUE TITLE
Release 0.2.0 roadmap

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar-manager#152]
###  Authentication and Authorization

Pulsar is a multi-tenancy system. It supports different authentication and authorization mechanisms. We need to add the support for authentication and authorization in Pulsar manager.

### Schema Management

Pulsar schema is a core feature for event streams. Pulsar manager should provide better support on schemas, such as querying different versions of schemas, managing schemas and compatibility checks, and so on.

### Functions and IO Connectors

Pulsar provides a lightweight computing framework - Pulsar Functions and a lightweight connector framework - Pulsar IO. We have done some initial work for supporting functions and connectors on version 0.0.1. We need to enable and complete the support for functions and IO connectors.

### BookKeeper Management

Pulsar uses Apache BookKeeper as its scale-out log storage for storing event streams. Managing bookies is the core of managing Pulsar. We should provide the capability to manage bookies.

### Support peek messages (include single and batch)

Peeking messages is a very useful mechanism for troubleshooting the problems in a production system. We need to add this support. The peek operations should support both single and batch messages, as well as messages encoded using different schemas.

### Backend Enhancement

Currently, most component data are loaded all at once. When the amount of data is relatively large, the user experience is very unfriendly. This part can be reasonably optimized through backend services.

**Comment by sunlc210** [comment]
Waiting for the new release ,BTW, can supply the binary tar ?The build work is too tough, must supply the non-conflict npm env.

**Comment by tuteng** [comment]
v0.2.0 has been released, we close it
