### ISSUE TITLE
For partitioned topics, show statistics correctly in namespace details

### ISSUE THREAD

**Issue by rocketraman** [apache/pulsar-manager#198]
The namespace details page currently does not show the correct statistics in the Producers, Subscriptions, or any of the Rate, Throughput, or Storage Size columns.

It does show that information per-partition in the Topic Details page.

Is it possible for the Namespace Details page to aggregate all of the information from each individual partition and show it?

**Comment by tuteng** [comment]
The timer has already saved the required statistics in the database, so it is relatively easy to aggregate these contents below. There is still a lot of work to be done in this part. Recently, I have not taken the time to do this part of the work. I may need to do this part of the work next week. Are you interested in trying to do something? @rocketraman

**Comment by rocketraman** [comment]
Just took a quick look at the code, and yeah, it looks pretty simple. Unfortunately I don't think I'll have the time to tackle this in the next little while though.

**Comment by tuteng** [comment]
Thank you, I am trying to take some time to deal with these issues in the next few weeks.

**Comment by tuteng** [comment]
This is fixed #239
