### ISSUE TITLE
Clean up dependency repositories

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar-manager#199]
Currently build.gradle is configured to download from unsecure sites, using plain http protocol.
We should only use https protocol and official and well known repositories.

We should drop http://maven.aliyun.com/nexus/content/groups/public and allow only 'Maven Central' and "Maven Local"

**Comment by eolivelli** [comment]
@tuteng I feel this is kind of a blocker for a release.
I am happy to send a patch

**Comment by tuteng** [comment]
You are right, thank you very much.

**Comment by eolivelli** [comment]
@tuteng here is the patch #200
