### ISSUE TITLE
Is that possible to deploy functions "Fat" jar in pulsar manager?

### ISSUE THREAD

**Issue by tcwmj** [apache/pulsar-manager#215]
Deploying functions "Fat" jar into Cloud Kubernetes is too tedious, Is that possible to deploy it in pulsar manager?

**Comment by tuteng** [comment]
After the latest release of version 0.1.0 of pulsar-manager is completed, we will provide YAML files based on k8s to make it easier for users to deploy on cloud platforms.

**Comment by tcwmj** [comment]
Excellent,
