### ISSUE TITLE
Unable to pull or find Docker image

### ISSUE THREAD

**Issue by Mountainerd** [apache/pulsar-manager#216]
Following the instructions, I am trying to pull apache/pulsar-manager and Docker is unable to find it. When I search Docker Hub, it only is able to find the streamnative/pulsar-manager image that was updated two months ago.

**Comment by tuteng** [comment]
Since this project was migrated to apache, the release has not yet been completed. we are currently making the first release. After the release is completed, we will release a new version of the image. now you can use this https://hub.docker.com/r/streamnative/pulsar-manager

**Comment by tuteng** [comment]
Docker image is now available https://hub.docker.com/r/apachepulsar/pulsar-manager

```
docker pull apachepulsar/pulsar-manager:v0.1.0
```

**Comment by jiazhai** [comment]
close this issue for it is resolved
