### ISSUE TITLE
Add TLS Authentication and Authorization Support

### ISSUE THREAD

**Issue by one70six** [apache/pulsar-manager#220]
Please add support for Pulsar clusters that utilize TLS authentication and authorization mechanisms. Pulsar Manager would be a welcome addition to existing clusters if the tool supported TLS.

[Authentication using TLS](https://pulsar.apache.org/docs/en/security-tls-authentication/)

Thanks!

**Comment by tuteng** [comment]
After supporting JWT authentication and authorization, I think it is relatively simple to support TLS authentication. I am currently working in this area and will add my support to TLS authentication.

**Comment by one70six** [comment]
Awesome @tuteng, looking forward to it!

**Comment by jiazhai** [comment]
This is dup to #224 would like to close this.
