### ISSUE TITLE
enable http -> https to redirection

### ISSUE THREAD

**Issue by KannarFr** [apache/pulsar-manager#224]
Is it possible to have a configuration that enable redirections from http to https on front and back? :)

**Comment by tuteng** [comment]
Currently, the forwarding of HTTP is hardcoded in the code https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java#L79. If broker turns on https, there may be a forwarding problem. I will try to fix this problem when supporting TLS authorization https://github.com/apache/pulsar-manager/issues/14.

**Comment by jiazhai** [comment]
This is a sub issue for #226

**Comment by jiazhai** [comment]
we need to provide a schema that support for http/https.

**Comment by sde-melo** [comment]
If it can helps someone, here is what I did to allow https redirection : https://github.com/Singlespot/pulsar-manager/commit/ef46449c07ac25a014df8ede031050406c546f9b.  Our Pulsar manager is behind a AWS load balancer that handles TLS.

**Comment by KannarFr** [comment]
Sure can you create PR upstream? :)

**Comment by sde-melo** [comment]
I have just noticed that our repo is not at all up-to-date. Moreover I am not sure that our changes covers all cases. But OK for the PR when it works again.

**Comment by KannarFr** [comment]
@sde-melo so what we do? ;)

**Comment by sde-melo** [comment]
@KannarFr I merged the last changes and have been unable to add an environment ever since because "User does not have permission to operate" so I couldn't test. In the meantime I had to switch to another subject.

**Comment by tuteng** [comment]
@sde-melo At present, in the latest code, pulsar-manager uses the database to manage users instead of configuration files. The superuser needs to be initialized at the first startup. I think you can solve this problem by initializing users.  https://github.com/apache/pulsar-manager#preparation 

```
curl -H "Content-Type: application/json" -X PUT http://backend-service:7750/pulsar-manager/users/superuser -d '{"name": "admin", "password": "apachepulsar", "description": "test", "email": "username@test.org"}'
```

**Comment by sde-melo** [comment]
@tuteng Thank you!  I had to make a few changes on docker/init_db.sql (https://github.com/Singlespot/pulsar-manager/commit/b2e411cfc2d77915abfc52e02423ebeb88aacf70) but I finally got it to work!

**Comment by tuteng** [comment]
I haven't updated the docker script yet. Now that you have succeeded, can you raise a pull request to improve this? @sde-melo Thanks

**Comment by sde-melo** [comment]
@tuteng It's done: https://github.com/apache/pulsar-manager/pull/263

**Comment by sde-melo** [comment]
I had nothing to change with the latest code.  It worked out of the box, without even having to set redirect.scheme to https.

**Comment by KannarFr** [comment]
@tuteng what is the status? :)

**Comment by sijie** [comment]
This feature has been supported in #258
