### ISSUE TITLE
Configuring environment through environment variables

### ISSUE THREAD

**Issue by sky-big** [apache/pulsar-manager#225]
It would be good to provide a default environment broker for K8s. then pulsar-manager will connect to it at start time.

For example:
ENVIRONMENT=["broker1", "broker2"]
@tuteng @wolfstudy 

Pulsar Operator want to set default broker to pulsar manager.

**Comment by jiazhai** [comment]
Seems this is more of a enhancement, not impact user to use this.  mark it as help-wanted

**Comment by sky-big** [comment]
Yes, it is.

**Comment by sijie** [comment]
This is fixed by #242
