### ISSUE TITLE
[Refactoring] Use Pulsar Admin instead of HttpUtil

### ISSUE THREAD

**Issue by shustsud** [apache/pulsar-manager#249]
Http request between BE and Brokers use [HttpUtil class](https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/utils/HttpUtil.java).
I think it's better to use [PulsarAdmin class](https://github.com/apache/pulsar/blob/master/pulsar-client-admin/src/main/java/org/apache/pulsar/client/admin/PulsarAdmin.java).

It has the following advantages:
- BE does not need to specify URL.
- BE does not need to consider namespace version.
- BE can use the authentication supported by Pulsar.

**Comment by tuteng** [comment]
You are right, I think most of the requests below can be implemented by pulsar-admin in https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/service/impl, but I suggest to keep the class `HttpUtil`, because it is very convenient to have an Http client at some time. @shustsud

**Comment by shustsud** [comment]
@tuteng
Yes, I don't think it is necessary to delete the HttpUtil class.
Is it OK to use Pulsar Admin instead of HttpUtil in [Service class](https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/service/impl)?

**Comment by tuteng** [comment]
Yes, you are right.

**Comment by shustsud** [comment]
@tuteng
[EnvironmentForward class](https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java) and [Controller class](https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/controller) receive HTTP from FE.
How does FE differentiate [EnvironmentForward class](https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java) from [Controller class](https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/controller)?

**Comment by tuteng** [comment]
> @tuteng
> [EnvironmentForward class](https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java) and [Controller class](https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/controller) receive HTTP from FE.
> How does FE differentiate [EnvironmentForward class](https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java) from [Controller class](https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/controller)?

[EnvironmentForward class](https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/zuul/EnvironmentForward.java) will forward most of the requests directly to the broker,
[Controller class](https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/controller) deals with information that needs to be aggregated, such as paging, filtering. @shustsud

**Comment by shustsud** [comment]
@tuteng
Thanks for your comment.
I understood the above.
