### ISSUE TITLE
Unable to add TLS secured environment

### ISSUE THREAD

**Issue by david-streamlio** [apache/pulsar-manager#253]
When I attempt to enter a url with https:, e.g. "https://localhost:8443" on the new environment box, I get an error.

![Screen Shot 2020-01-30 at 4 46 37 PM](https://user-images.githubusercontent.com/35466513/73503130-3a3a5e00-4380-11ea-947b-8ce32d005460.png)

Please allow the manager to support TLS secured Pulsar clusters

**Comment by tuteng** [comment]
I am very sorry that this feature has been delayed for too long. I will spend some time to fix this one recently. @david-streamlio

**Comment by eilonk** [comment]
any estimate to when this would be resolved?

**Comment by sijie** [comment]
@eilonk this feature has been implemented in #258. 

@tuteng we should consider cutting a release for pulsar-manager.
