### ISSUE TITLE
Token Creation generates error Token gennerate failed

### ISSUE THREAD

**Issue by vshulkin** [apache/pulsar-manager#260]
I can't create tokens from pulsar-manager.  New Token screen generates error
Token gennerate failed.  Authn/Authz enabled and secret key JWT token was setup.  Please help.

**Comment by tuteng** [comment]
Can you show me more detailed information? for example, is it based on image construction or self-build project base master code? Can't you click on the page, can't generate tokens? Is the cluster or standalone environment used? Has JWT authentication been enabled for the cluster, and can it be accessed normally with pulsar-admin? Thanks to @vshulkin

**Comment by vshulkin** [comment]
Hi I am using both docker image 2.4.0 and 2.5.0 and packaged distribution.
JWT enabled and I can access the cluster. I used both standalone and
cluster environment. So everything works fine with the exception of token
generation.

**Comment by vshulkin** [comment]
![Capture1](https://user-images.githubusercontent.com/12044899/74115368-f106bd00-4b7c-11ea-9fe7-6dff47530051.JPG)
![Capture2](https://user-images.githubusercontent.com/12044899/74115369-f237ea00-4b7c-11ea-8893-f7b904da7d92.JPG)
![Capture3](https://user-images.githubusercontent.com/12044899/74115370-f237ea00-4b7c-11ea-8f05-8dc84c9179a3.JPG)

**Comment by vshulkin** [comment]
I don't see any http requests hitting broker when I press generate the token.  I assume it suppose to trigger REST API call.

**Comment by tuteng** [comment]
Do you start the service according to the following method https://github.com/apache/pulsar-manager/tree/master/src#enable-jwt-auth, have you configured this option `backend.jwt.token=token` @vshulkin

**Comment by vshulkin** [comment]
Yes.  Token was enabled.

export SECRET_KEY=data:base64,WnBwcHdrvwk197xbpoI8SEPp5FNOf7QGPOvhtDxVXzA=
export JWT_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiJ9.52xJy4uz5C0mtuuQCpciqhngq-l4YmGIFkzt88ACFkc


docker run -it -p 9527:9527 -e REDIRECT_HOST=http://192.168.55.182 -e REDIRECT_PORT=9527 -e DRIVER_CLASS_NAME=org.postgresql.Driver -e URL='jdbc:postgresql://127.0.0.1:5432/pulsar_manager' -e USERNAME=pulsar -e PASSWORD=pulsar -e LOG_LEVEL=DEBUG -e SECRET_KEY=$SECRET_KEY -e JWT_TOKEN=$JWT_TOKEN -e PRIVATE_KEY=$PRIVATE_KEY -e PUBLIC_KEY=$PUBLIC_KEY -v $PWD:/data apachepulsar/pulsar-manager:v0.1.0 /bin/sh


This is how I run pulsar manager

**Comment by vshulkin** [comment]
I think I found an issue.  jwt.broker.token.mode=SECRET has to be set

**Comment by tuteng** [comment]
Have you solved the problem? Can we close the issue? @vshulkin Thanks.

**Comment by vshulkin** [comment]
Yes. I resolve the issue. However I recommend to update the instructions
and supervisord-secret-key.conf file and include
jwt.broker.token.mode=SECRET into the startup line. Because there is no way
to pass this through env variable to docker run.

**Comment by vshulkin** [comment]
This line should be

command = /pulsar-manager/pulsar-manager/bin/pulsar-manager  --redirect.host=%(ENV_REDIRECT_HOST)s --redirect.port=%(ENV_REDIRECT_PORT)s --spring.datasource.driver-class-name=%(ENV_DRIVER_CLASS_NAME)s --spring.datasource.url=%(ENV_URL)s --spring.datasource.username=%(ENV_USERNAME)s --spring.datasource.password=%(ENV_PASSWORD)s --spring.datasource.initialization-mode=never --logging.level.org.apache=%(ENV_LOG_LEVEL)s --jwt.broker.token.mode=SECRET --backend.jwt.token=%(ENV_JWT_TOKEN)s --jwt.broker.secret.key=%(ENV_SECRET_KEY)s

**Comment by tuteng** [comment]
@vshulkin Thank you for your feedback. Can you help me with open a PR to fix this problem?

**Comment by vshulkin** [comment]
Opened the PR.
