### ISSUE TITLE
pulls manager error at New Environment

### ISSUE THREAD

**Issue by rohitbacknan** [apache/pulsar-manager#261]
Pulse manager is continuously throwing error:
{"error":"This environment is error. Please check it"}.
Cannot even move ahead to next page

**Comment by rohitbacknan** [comment]
Issue exists with the docker image

**Comment by tuteng** [comment]
> Pulse manager is continuously throwing error:
> {"error":"This environment is error. Please check it"}.
> Cannot even move ahead to next page

This problem usually occurs when you enter the environment for the first time. It seems that your `serviceUrl` is not configured correctly. It should be prefixed with `http`, and ensure that the machine of system pulsar-manager is connected to the network of your Pulsar cluster. @rohitbacknan

**Comment by rohitbacknan** [comment]
Thank you so much. I deployed the docker image and service url had to be provided for the local system ip.
