### ISSUE TITLE
Run static frontend HTML files from the embedded SprintBoot server

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar-manager#269]
Currently we need two separate web servers to run Pulsar Manager.
It would be more user friendly to run only a single process.
As we are already starting a webserver for the backend it would be super easy to map the static content inside "dist" to an HTTP path.

This is what we are doing in [BookKeeper Visual Manager](https://github.com/diennea/bookkeeper-visual-manager).

This way with a single command bin/pulsar-manager you will be up and running in one minute after downloading the release package.

I am happy to contribute a patch if this idea is interesting for the community

**Comment by tuteng** [comment]
I'm very sorry for the late reply, this is a very good feature, very welcome to contribute. @eolivelli

**Comment by sijie** [comment]
@eolivelli +1 for the idea

**Comment by eolivelli** [comment]
I will do.
I will try to spend some time in the weekend, hopefully we could include this change in the upcoming release

**Comment by eolivelli** [comment]
@tuteng @sijie  thanks for merging the patch
we should now update the release procedure in a way that the frontend is copied inside the binary distribution tarball inside the 'ui' directory.

Any suggestion ? I can try to do this follow up change but I don't know where to start
