### ISSUE TITLE
No delete, No unload and clear.

### ISSUE THREAD

**Issue by oeegee** [apache/pulsar-manager#270]
Dear developers,
I'm installing and testing now trying to use pulsar.
Successfully installed pulsar and pulsar manager and even ran.
However, in pulsar-manager I can't make any updates.

The error message is as follows:

It is created, but not deleted or updated.
cluster, tenant, namespace, and topic are all equivalents.

Here are error message in pulsar-manager backend:
**(truncated address)**
`2020-03-04 10:46:08.630 ERROR 8043 --- [http-nio-7750-exec-6] o.a.p.manager.zuul.EnvironmentForward    : Route forward to http://172.21.42.34:8080,172.19.115.33:8080,172.21.43.41:8080 path /admin/v2/clusters/dev-pulsar error: For input string: "8080,172.19.115.33:8080,172.21.43.41:8080"`

Here are service url (auto completion 3 cluster, only input first cluster's address ): 
![image](https://user-images.githubusercontent.com/497211/75836956-ce2b9980-5e06-11ea-84aa-a45deabd526e.png)

![image](https://user-images.githubusercontent.com/497211/75836928-b6541580-5e06-11ea-8f10-835dff6c5b18.png)

![image](https://user-images.githubusercontent.com/497211/75836945-c3710480-5e06-11ea-992a-2e09aa8058c2.png)

**Comment by sijie** [comment]
@oeegee current it doesn't support multi-hosts service url.

**Comment by sijie** [comment]
Can you change the service url to single host service url?

**Comment by sijie** [comment]
@oeegee 

You can use `bin/pulsar-admin clusters update` command to change the web-service-url for that cluster. Because pulsar-manager will read the cluster configuration and use that `web-service-url` to access the cluster.

**Comment by oeegee** [comment]
@sijie , OK. 
I solved the problem using L4 VIP based on what you told me.
Thank you~!
