### ISSUE TITLE
Handle broker 307 redirect

### ISSUE THREAD

**Issue by tuteng** [apache/pulsar-manager#274]
In pulsar, each topic is handled by a broker. Therefore, for creating, updating and deleting topics, requests will be sent to any broker. If the broker finds that it cannot handle the request of this topic, it will return a 307 and redirect it to the correct broker. In pulsar-manager, the current redirection is handled by the front end. There are some unreasonable points in this:

1. Expose too much information for the front end
2. sometimes the address of load balance cannot be obtained in k8s deployment.

Therefore, consider the following optimization method

1. spring boot takes over zuul's route forwarding. After acquiring the topic, it directly calculates the correct broker address and forwards the request to it.

2. Introduce pulsar-proxy dependency and make some improvements to process 307 requests

**Comment by YanshuoH** [comment]
hi, any update on this?

**Comment by thomasechen** [comment]
Dear All,

 This issue would lead to the Pulsar manager sometime could not create topic and subscription if the cluster has multiple brokers in it .

[URL: https://github.com/apache/pulsar-manager/issues/449#issuecomment-1061484123](https://github.com/apache/pulsar-manager/issues/449#issue-1162280548)
