### ISSUE TITLE
Could we add a dashboard in the home page ?

### ISSUE THREAD

**Issue by tangshihui** [apache/pulsar-manager#282]
In the dashboard, we can display the statistics: 

- Total clusters
- Total tenants
- Total namespaces
- Total topics
- Total producers
- Total consumers
- Total brokers
- Total bookies

**Comment by tuteng** [comment]
Yes, I think this is a good idea. I'll mark it help-wanted first. If anyone wants to do it, please refer to the following step.

1. Get the total number of `cluster`, `tenant`, `namespace`, `topic`, `producer`, `consumer`, `broker` and `bookie`, refer to this implementation https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/mapper/TopicsStatsMapper.java.
2. Add dao Layer Implementation https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/dao/TopicsStatsRepositoryImpl.java
3. Add Service layer Interface and implement => https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/service
4. Add controller => https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/controller
5. Add unit tests => https://github.com/apache/pulsar-manager/blob/master/src/test/java/org/apache/pulsar/manager/
6. Add front-end interface => https://github.com/apache/pulsar-manager/blob/master/front-end/src/api
7. Add front page => https://github.com/apache/pulsar-manager/tree/master/front-end/src/views/management

More information: https://github.com/apache/pulsar-manager/blob/master/CONTRIBUTING.md

@tangshihui

**Comment by Omega-Ariston** [comment]
> Yes, I think this is a good idea. I'll mark it help-wanted first. If anyone wants to do it, please refer to the following step.
> 
> 1. Get the total number of `cluster`, `tenant`, `namespace`, `topic`, `producer`, `consumer`, `broker` and `bookie`, refer to this implementation https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/mapper/TopicsStatsMapper.java.
> 2. Add dao Layer Implementation https://github.com/apache/pulsar-manager/blob/master/src/main/java/org/apache/pulsar/manager/dao/TopicsStatsRepositoryImpl.java
> 3. Add Service layer Interface and implement => https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/service
> 4. Add controller => https://github.com/apache/pulsar-manager/tree/master/src/main/java/org/apache/pulsar/manager/controller
> 5. Add unit tests => https://github.com/apache/pulsar-manager/blob/master/src/test/java/org/apache/pulsar/manager/
> 6. Add front-end interface => https://github.com/apache/pulsar-manager/blob/master/front-end/src/api
> 7. Add front page => https://github.com/apache/pulsar-manager/tree/master/front-end/src/views/management
> 
> More information: https://github.com/apache/pulsar-manager/blob/master/CONTRIBUTING.md
> 
> @tangshihui

Working on it, but have one question, when doing step 1, can I just simply just call the services for cluster, tenant, namespace... seperately and gather the result, instead of writing sql statements myself in `TopicsStatsMapper.java` ? Since the latter implementation needs to take the type of users(super or normal user) into account.

**Comment by tuteng** [comment]
I'm very sorry to reply late. If you just query the statistical information of a tenant, a namespace, or a topic, you can call the cluster service directly. But for the dashboard, what users need more is aggregated information, such as statistical information of multiple tenants, multiple namespaces, and multiple topics. If you call the cluster service circularly, the cost is very high. We collect statistical information regularly by adding timed tasks mainly for the aggregation calculation of various resources. @Omega-Ariston Thanks

**Comment by Omega-Ariston** [comment]
> I'm very sorry to reply late. If you just query the statistical information of a tenant, a namespace, or a topic, you can call the cluster service directly. But for the dashboard, what users need more is aggregated information, such as statistical information of multiple tenants, multiple namespaces, and multiple topics. If you call the cluster service circularly, the cost is very high. We collect statistical information regularly by adding timed tasks mainly for the aggregation calculation of various resources. @Omega-Ariston Thanks

All good bud :) I am currently thinking about what the UI interface looks like and I wonder if there is an existing design of the dashboard or any preference? And the task is to add a dashboard in the home page. Is the 'home page' an existing page or do we need to add a new one and direct users to this new page after their login?
