### ISSUE TITLE
/admin/v2   is 404 not found  /pulsar-manager/admin/v2 is ok

### ISSUE THREAD

**Issue by jiangmincong** [apache/pulsar-manager#304]
Why do requests with url starting with /admin/v2 report a 404 error, and /pulsar-manager/admin/v2 is indeed normal；
My nginx configuration is as follows:
server {
listen 9527;
server_name localhost;

location / {
root /root/pulsar-manage/dist;
index index.html index.htm;
}
location /admin {
proxy_pass http://localhost:7750;
}
location /pulsar-manager {
proxy_pass http://localhost:7750;
}
location /lookup {
proxy_pass http://localhost:7750;
}
}

**Comment by tuteng** [comment]
How do you deploy the environment, build it yourself or use containers, do your front-end and back-end services work together, do your cluster environment startup, and you can try the following command to test your cluster

Use curl:
```
curl -v http://broker-ip:8080/metrics/
```

Use pulsar-admin

```
pulsar-admin tenants list
```

@jiangmincong

**Comment by jiangmincong** [comment]
I found the reason, the pulsar-manager and github code I downloaded from apache pulsar is different
