### ISSUE TITLE
Postgres DB not created when starting up Pulsar Manager

### ISSUE THREAD

**Issue by nikeshhajari** [apache/pulsar-manager#336]
Hi -

I was following the tutorial, but on start-up of the docker container I receive this message ---

running bootstrap script ... 2020-09-14 23:26:07.962 UTC [41] FATAL:  data directory "/data/postgresql" has wrong ownership
2020-09-14 23:26:07.962 UTC [41] HINT:  The server must be started by the user that owns the data directory.
child process exited with exit code 1
initdb: removing contents of data directory "/data/postgresql"
pg_ctl: directory "/data/postgresql" is not a database cluster directory
createdb: could not connect to database template1: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

My understanding is the pulsar manager has its own PostGres database built in. I can login to the manager, but nothing works because the DB isn't initialized.

**Comment by jiazhai** [comment]
@nikeshhajari You are right, seems the db not initialized.
