### ISSUE TITLE
when setting `user.management.enable=false` the user `pulsar-manager.account` does not have admin role.

### ISSUE THREAD

**Issue by mingfang** [apache/pulsar-manager#347]
when setting `user.management.enable=false` the user `pulsar-manager.account` does not have admin role.

The problem seems to be here.

https://github.com/apache/pulsar-manager/blob/0bd2f8a04b09c536f7001fecae0d0e926a46f8bd/src/main/java/org/apache/pulsar/manager/controller/LoginController.java#L135

**Comment by sijie** [comment]
@mingfang Are you interested in contributing a bug fix?
