### ISSUE TITLE
Upgrade BKVM to 3.0.0

### ISSUE THREAD

**Issue by eolivelli** [apache/pulsar-manager#359]
We should upgrade BKVM to 3.0.0, release highlights:
- support for multiple BookKeeper/Pulsar clusters
- improved usability
- upgrade of HerdDB

With this change it is better to upgrade HerdDB to 0.22.0 and Pulsar to 2.7.0 (and BK implicitly to 4.12.0)

**Comment by dianacle** [comment]
I'll try to do that.
