### ISSUE TITLE
Pulsar manager's swagger dose not work. 

### ISSUE THREAD

**Issue by zsh0139** [apache/pulsar-manager#361]
When I access the back-end path of  "/swagger-ui.html" in the development environment, it prompts me that 401 is not authorized. I think it should ignore swagger's access rights

**Comment by chuyuqiao** [comment]
I encounter too.the reason is that AdminHandlerInterceptor validate token.

**Comment by yixing1337** [comment]
I will push a pr to fix this issue

**Comment by tuteng** [comment]
This is fixed #369 Thanks @yixing1337
