### ISSUE TITLE
Some mistakes in README.md of the master branch

### ISSUE THREAD

**Issue by yixing1337** [apache/pulsar-manager#365]
in README.md of the master branch, there are some contents below.

**Build from bin package**
wget https://dist.apache.org/repos/dist/release/pulsar/pulsar-manager/apache-pulsar-manager-0.2.0/apache-pulsar-manager-0.2.0-bin.tar.gz
...
tar -zxvf pulsar-manager.tar
...

But there are two mistakes in the above content.
**first:**
`wget https://dist.apache.org/repos/dist/release/pulsar/pulsar-manager/apache-pulsar-manager-0.2.0/apache-pulsar-manager-0.2.0-bin.tar.gz` return 404 error code
![Snipaste_2020-12-23_10-13-06](https://user-images.githubusercontent.com/5304046/102954800-52bee400-450f-11eb-8fc1-e836b0b7dc2e.png)

**second:**
`tar -zxvf pulsar-manager.tar` not working
![Snipaste_2020-12-23_10-13-38](https://user-images.githubusercontent.com/5304046/102954810-56526b00-450f-11eb-8694-7e86f4587ac4.png)

**Comment by yixing1337** [comment]
Please assign me, I will push a pr and fix the two mistakes. Thank you!

**Comment by tuteng** [comment]
This is fixed #184
