### ISSUE TITLE
Starting Pulsar manager using Docker Compose does not take default username/ password of pulsar/ pulsar

### ISSUE THREAD

**Issue by hsaputra** [apache/pulsar-manager#378]
I tried to use the latest from master to run `docker-compose up` to start Pulsar and Pulsar Manager.

Connecting to http://localhost:9527/#/environments and try enter default username/password of pulsar/ pulsar keep returning error:

```
The username or password is incorrect
```

I did not see anything in the console message.

**Comment by DidierSchonne** [comment]
@hsaputra If you read the docs: https://github.com/apache/pulsar-manager#access-pulsar-manager
You can see that you have to run a CURL command to create the first user.

**Comment by hsaputra** [comment]
Ah ok, the doc was not clear that I must do this. I thought there was already a built in user as part of bootstrap

**Comment by DidierSchonne** [comment]
Did you manage to pass the following screen?
If I try to add an environment, and I'm sure that the URL is good, I got this error message:
"error
This environment is error. Please check it"

**Comment by DidierSchonne** [comment]
Ok, I was able to add an environment, replacing localhost or 127.0.0.1 by the docker network ip created by the Pulsar docker-compose.

**Comment by hsaputra** [comment]
Have not gotten chance to try it out. Will do in  the next couple of days. Will close this one for now.
