### ISSUE TITLE
http://backend:7750/swagger-ui.html is throwing {"message":"Please login."}

### ISSUE THREAD

**Issue by abenbouz** [apache/pulsar-manager#391]
hello
i have tested last release 0.2.1 but i have an issue with pulsar manager swagger ui
when i access the url http://backend:7750/swagger-ui.html i have the flowing error :

{"message":"Please login."}

have any idea on how to solve that ?
Thanks

**Comment by tuteng** [comment]
https://github.com/apache/pulsar-manager/blob/master/src/main/resources/application.properties#L158 
Please enable this option @abenbouz

**Comment by tisonkun** [comment]
I think we can enable swagger by default. PR preparing...
