### ISSUE TITLE
Failed to login pulsar-manager in docker

### ISSUE THREAD

**Issue by xiaozongyang** [apache/pulsar-manager#399]
# What I see
I deploy a pulsar-manager instance in docker following these instructions. When I try to login in my browser, I got a 404 error shown in following picture.
![image](https://user-images.githubusercontent.com/8848479/122704821-0c143180-d287-11eb-9b56-24d6aeef00e6.png)

![image](https://user-images.githubusercontent.com/8848479/122704898-32d26800-d287-11eb-8033-16dfc009ca0e.png)

This request is copied as curl in this command,
```bash
curl 'http://localhost:9527/pulsar-manager/login' \
  -H 'Connection: keep-alive' \
  -H 'Pragma: no-cache' \
  -H 'Cache-Control: no-cache' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'X-XSRF-TOKEN: undefined' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36' \
  -H 'tenant: undefined' \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'environment: undefined' \
  -H 'username: undefined' \
  -H 'Origin: http://localhost:9527' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: http://localhost:9527/' \
  -H 'Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7' \
  -H 'Cookie: _xsrf=2|4013fd3e|b6d98ef38bbba404502e0a5149e81de2|1624113166; username-localhost-8888="2|1:0|10:1624191319|23:username-localhost-8888|44:MWE3Y2Y2NWNmYTU2NGVlNDg4YjkyMWExMWYzYmM0YmQ=|b3644b7048dd362805f83e20ffd3287039a86c6b8df75b01360fddfe066e35cc"' \
  --data-raw '{"username":"admin","password":"apachepulsar"}' \
  --compressed
```

# Expected behavior
Login successfully and redirect to the admin page.

# Actual behavior
No UI response and got 404 error in console.

**Comment by tuteng** [comment]
Which version of the image are you using, and can you show the command you are using? @xiaozongyang

**Comment by xiaozongyang** [comment]
@tuteng The image version is v0.2.0, shown in the following picture.
![image](https://user-images.githubusercontent.com/8848479/122941973-6f49b500-d3a8-11eb-89a3-0eb281a488d7.png)

Running container use this command, 
```bash
docker run -it \
    -p 9527:9527 -p 7750:7750 \
    -e SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties \
    apachepulsar/pulsar-manager:v0.2.0
```

**Comment by tuteng** [comment]
@xiaolongge904913 I think you can try this host: http://localhost:9527/, It will automatically redirect to the login address `http://localhost:9527/#/login?redirect=%2F`, also don't forget to initialize your login account and password https://github.com/apache/pulsar-manager#access-pulsar-manager

**Comment by xiaozongyang** [comment]
@tuteng   THX, it works! This issue will be closed.

**Comment by dongze1213** [comment]
@tuteng hi, i had the same problem, could you help ?

**Comment by ton3r** [comment]
I've installed the helm chart from pulsar. The first call to the manager works fine. But after that, everything have a 404. So login or even "set up an super user" is not possible. At least that there isn't any service providing port 7750 with helmcharts

![pulsar](https://github.com/apache/pulsar-manager/assets/10545359/f56d0ba5-1d11-4ffe-85cb-1ac6cddbd291)

**Comment by huyinghuan** [comment]
> I've installed the helm chart from pulsar. The first call to the manager works fine. But after that, everything have a 404. So login or even "set up an super user" is not possible. At least that there isn't any service providing port 7750 with helmcharts
> 
> ![pulsar](https://private-user-images.githubusercontent.com/10545359/286963541-f56d0ba5-1d11-4ffe-85cb-1ac6cddbd291.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDY1ODcsIm5iZiI6MTcwNTk0NjI4NywicGF0aCI6Ii8xMDU0NTM1OS8yODY5NjM1NDEtZjU2ZDBiYTUtMWQxMS00ZmZlLTg1Y2ItMWFjNmNkZGJkMjkxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE3NTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZmE4N2U0M2M0YTk0NzQ2ZWFlNDZhODNkYTYxOWY1MjhhZDc2MmE0N2U5NWQ1NTc3YWJjYThmNzU2NTNlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cJLNFmsOggnPqXTJAeKsQEklmJfyRATd4wsf71FXLbI) [ ![pulsar](https://private-user-images.githubusercontent.com/10545359/286963541-f56d0ba5-1d11-4ffe-85cb-1ac6cddbd291.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDY1ODcsIm5iZiI6MTcwNTk0NjI4NywicGF0aCI6Ii8xMDU0NTM1OS8yODY5NjM1NDEtZjU2ZDBiYTUtMWQxMS00ZmZlLTg1Y2ItMWFjNmNkZGJkMjkxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE3NTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZmE4N2U0M2M0YTk0NzQ2ZWFlNDZhODNkYTYxOWY1MjhhZDc2MmE0N2U5NWQ1NTc3YWJjYThmNzU2NTNlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cJLNFmsOggnPqXTJAeKsQEklmJfyRATd4wsf71FXLbI) ](https://private-user-images.githubusercontent.com/10545359/286963541-f56d0ba5-1d11-4ffe-85cb-1ac6cddbd291.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDY1ODcsIm5iZiI6MTcwNTk0NjI4NywicGF0aCI6Ii8xMDU0NTM1OS8yODY5NjM1NDEtZjU2ZDBiYTUtMWQxMS00ZmZlLTg1Y2ItMWFjNmNkZGJkMjkxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE3NTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZmE4N2U0M2M0YTk0NzQ2ZWFlNDZhODNkYTYxOWY1MjhhZDc2MmE0N2U5NWQ1NTc3YWJjYThmNzU2NTNlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cJLNFmsOggnPqXTJAeKsQEklmJfyRATd4wsf71FXLbI) [ ](https://private-user-images.githubusercontent.com/10545359/286963541-f56d0ba5-1d11-4ffe-85cb-1ac6cddbd291.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5NDY1ODcsIm5iZiI6MTcwNTk0NjI4NywicGF0aCI6Ii8xMDU0NTM1OS8yODY5NjM1NDEtZjU2ZDBiYTUtMWQxMS00ZmZlLTg1Y2ItMWFjNmNkZGJkMjkxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIyVDE3NTgwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZmE4N2U0M2M0YTk0NzQ2ZWFlNDZhODNkYTYxOWY1MjhhZDc2MmE0N2U5NWQ1NTc3YWJjYThmNzU2NTNlYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cJLNFmsOggnPqXTJAeKsQEklmJfyRATd4wsf71FXLbI)

I have same error
