### ISSUE TITLE
manager UI login 404

### ISSUE THREAD

**Issue by gangming** [apache/pulsar-manager#476]
<img width="638" alt="WX20220729-154813@2x" src="https://user-images.githubusercontent.com/15102743/181711118-fdeb67d7-2247-49f8-9185-a0c5465775ab.png">
command:

`docker run -it \
    -p 9527:9527 -p 7750:7750 \
    -e SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties \
    apachepulsar/pulsar-manager:v0.2.0`
platform: apple m1

**Comment by moecasts** [comment]
I have the same problem too, do you have solve it?

**Comment by Asongguo** [comment]
pulsar-manager进程没启动成功
![image](https://user-images.githubusercontent.com/29701800/182518128-410c33c9-bb24-4bdb-b7a5-7bde5f52d53a.png)

**Comment by moecasts** [comment]
> pulsar-manager进程没启动成功 ![image](https://user-images.githubusercontent.com/29701800/182518128-410c33c9-bb24-4bdb-b7a5-7bde5f52d53a.png)

这个需要怎么解决呢？我试了下就只有 m1 的会有这个问题，直接在 linux x86 上跑的话就正常。

**Comment by Asongguo** [comment]
问题是

**Comment by Asongguo** [comment]
问题是

**Comment by moecasts** [comment]
> 我查了下，根本问题pg没初始化成功，initdb， pg_ctl 这两个命令不在系统环境变量里面 ![image](https://user-images.githubusercontent.com/29701800/182519886-5eee108d-2005-484a-b69f-07f73ea5a1a3.png)
> 
> 解决办法是在这个文件第20行加入export PATH=$PATH:/usr/lib/postgresql/13/bin/ 就行了 ![image](https://user-images.githubusercontent.com/29701800/182519546-1890afb9-684c-4bbe-9e29-3d323a56d93d.png)

可以了，谢谢大佬！
