### ISSUE TITLE
The front-end compiled node version is faulty

### ISSUE THREAD

**Issue by g0715158** [apache/pulsar-manager#512]
The node version must be between 12.0.0 and 12.22.10 at compile time.
However, it was discovered at compile time that the component required a node version higher than 14
For example：
warning mini-css-extract-plugin@0.4.1: Invalid bin field for "mini-css-extract-plugin".
error commander@10.0.0: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.21.0"
error Found incompatible module.

**Comment by tisonkun** [comment]
We change the Node version in 0.4.0. Please check and open a new issue if it still doesn't work.
