### ISSUE TITLE
[front end] There is a warning message when running 'npm run dev'

### ISSUE THREAD

**Issue by linkun-wang** [apache/pulsar-manager#520]
[**front end**] There is a warning message when running `npm run dev`: [WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.]  
![plusarManager前端项目运行报错信息](https://github.com/apache/pulsar-manager/assets/33945539/5905bc44-8abb-4d72-a1e8-57388dc0fca7)

**Comment by tisonkun** [comment]
I don't think we should fix warning in compile time.

If you have a solution to suppress it, feel free to directly submit a patch. This can be something nice to have but not a bug.
